services:
  valtixcube_dev:
    image: valtixcube:dev            # ⭐ REQUIRED
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: ["npm", "start"]
