services:
  valtixcube_qa:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: valtixcube_qa
    ports:
      - "3002:3000"                       # Map port 3000 in container to port 3002 on host
    command: npm run start