name: valtixcube CD
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Dev Server
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /app/valtixcube_dev
            git pull origin dev
            docker compose down
            docker build --no-cache -t valtixcube_dev .
            docker compose up -d --no-build
  
  deploy-qa:
    name: QA Server
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Deploy via ssh
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /app/valtixcube_qa
            git pull origin dev
            docker compose down
            docker build --no-cache -t valtixcube_qa .
            docker compose up -d --no-build