name: Next.js CI + CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  # ----------------------------
  # CI - BUILD CHECK
  # ----------------------------
  build:
    name: CI - Build Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build


  # ----------------------------
  # CD - DEPLOY DEV
  # ----------------------------
  deploy-dev:
    name: Deploy Dev
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: SSH Deploy to Dev
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /app/valtixcube_dev
            git pull origin dev

            docker compose down --remove-orphans

            # CLEAN DISK
            docker system prune -af --volumes || true

            docker image rm -f valtixcube:latest || true

            docker build --no-cache --pull -t valtixcube:latest .
            docker compose up -d --force-recreate


  # ----------------------------
  # CD - DEPLOY QA
  # ----------------------------
  deploy-qa:
    name: Deploy QA
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: SSH Deploy to QA
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /app/valtixcube_dev

            docker compose up -d --force-recreate
